### ISSUE TITLE
mbyte character support

### ISSUE THREAD

**Issue by suliveevil** [itchyny/vim-cursorword#25]
Would you please add mbyte character support?

Underline all the same single character  in range `[\u4e00-\u9fa5] `is all I need.

Thank you very much.

**Comment by itchyny** [comment]
This plugin already supports some [multi-byte alphabets](https://github.com/itchyny/vim-cursorword/blob/cc8114226ceefb5cafe1890e0900d3efb7dab1fd/autoload/cursorword.vim#L21). But I cannot accept adding such a wider range characters because it doesn't work with `set regexpengine=1`. I don't think adding Chinese characters is useful because the entire line will be underlined.

**Comment by suliveevil** [comment]
You are right, underline a character is meaningless, I should find a way to achieve it when using `*`.
